# Generated by Django 4.2.27 on 2026-01-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_client_iva_rate'),
        ('billing', '0004_invoice_metadata'),
    ]

    operations = [
    ]
